require "log"

module Matter
  module Controller
    module CertificateUtil
      extend self

      Log = ::Log.for("matter.controller.certificate_util")

      # Extract the 65-byte uncompressed EC public key from a DER-encoded CSR.
      #
      # This implementation is intentionally minimal: it scans for a BIT STRING
      # containing an uncompressed P-256 point (0x04 || x || y) as generated by
      # `OperationalCredentials#build_csr_der`.
      def extract_uncompressed_public_key_from_csr(csr_der : Bytes) : Bytes
        i = 0
        while i < csr_der.size - 4
          if csr_der[i] == 0x03_u8
            length, length_bytes = parse_der_length(csr_der, i + 1)
            bit_string_start = i + 1 + length_bytes

            if length == 66 && bit_string_start + 66 <= csr_der.size
              unused_bits = csr_der[bit_string_start]
              marker = csr_der[bit_string_start + 1]

              if unused_bits == 0_u8 && marker == 0x04_u8
                return csr_der[bit_string_start + 1, 65]
              end
            end
          end
          i += 1
        end

        raise Matter::CertificateError.new("CSR public key not found")
      rescue ex
        Log.error(exception: ex) { "Failed extracting public key from CSR (csr_hex=#{csr_der.hexstring})" }
        raise ex
      end

      private def parse_der_length(data : Bytes, offset : Int32) : {Int32, Int32}
        first = data[offset]?
        raise Matter::CodecError.new("DER length out of bounds") unless first

        if first < 0x80
          {first.to_i, 1}
        else
          count = (first & 0x7f).to_i
          raise Matter::CodecError.new("DER length uses indefinite form") if count == 0
          raise Matter::CodecError.new("DER length out of bounds") if offset + count >= data.size

          length = 0
          count.times do |idx|
            length = (length << 8) | data[offset + 1 + idx].to_i
          end
          {length, 1 + count}
        end
      end
    end
  end
end
