module Matter
  module Cluster
    module Definitions
      module Groups
        alias StatusCode = Protocol::Interaction::StatusCode

        # Input to the Groups addGroup command
        struct AddGroupRequest
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property group_id : DataType::GroupId

          @[TLV::Field(tag: 1)]
          property group_name : String
        end

        # The AddGroupResponse is sent by the Groups cluster server in response to an AddGroup command.
        struct AddGroupResponse
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property status_code : StatusCode

          @[TLV::Field(tag: 1)]
          property group_id : DataType::GroupId
        end

        # Input to the Groups viewGroup command
        struct ViewGroupRequest
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property group_id : DataType::GroupId
        end

        # The ViewGroupResponse command is sent by the Groups cluster server in response to a ViewGroup command.
        struct ViewGroupResponse
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property status_code : StatusCode

          @[TLV::Field(tag: 1)]
          property group_id : DataType::GroupId

          @[TLV::Field(tag: 2)]
          property group_name : String
        end

        # Input to the Groups getGroupMembership command
        struct GetGroupMembershipRequest
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property group_list : Array(DataType::GroupId)
        end

        # The GetGroupMembershipResponse command is sent by the Groups cluster server in response to a GetGroupMembership
        # command.
        #
        # The fields of the GetGroupMembershipResponse command have the following semantics:
        #
        # The Capacity field shall contain the remaining capacity of the Group Table of the node. The following values
        # apply:
        #
        #   • 0 - No further groups may be added.
        #
        #   • 0 < Capacity < 0xfe - Capacity holds the number of groups that may be added.
        #
        #   • 0xfe - At least 1 further group may be added (exact number is unknown).
        #
        #   • null - It is unknown if any further groups may be added.
        #
        # The GroupList field shall contain either the group IDs of all the groups in the Group Table for which the server
        # endpoint is a member of the group (in the case where the GroupList field of the received GetGroupMembership
        # command was empty), or the group IDs of all the groups in the Group Table for which the server endpoint is a
        # member of the group and for which the group ID was included in the the GroupList field of the received
        # GetGroupMembership command (in the case where the GroupList field of the received GetGroupMembership command was
        # not empty).
        #
        # Zigbee: If the total number of groups will cause the maximum payload length of a frame to be exceeded, then the
        # GroupList field shall contain only as many groups as will fit.
        struct GetGroupMembershipResponse
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property capacity : UInt8?

          @[TLV::Field(tag: 1)]
          property group_list : Array(DataType::GroupId)
        end

        # Input to the Groups removeGroup command
        struct RemoveGroupRequest
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property group_id : DataType::GroupId
        end

        # The RemoveGroupResponse command is generated by the server in response to the receipt of a RemoveGroup command.
        struct RemoveGroupResponse
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property status_code : StatusCode

          @[TLV::Field(tag: 1)]
          property group_id : DataType::GroupId
        end

        # Input to the Groups addGroupIfIdentifying command
        struct AddGroupIfIdentifyingRequest
          include TLV::Serializable

          @[TLV::Field(tag: 0)]
          property group_id : DataType::GroupId

          @[TLV::Field(tag: 1)]
          property group_name : String
        end
      end
    end
  end
end
